/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/_module.d.ts:
/**
 * @constructor
 * @struct
 * @param {string} id
 * @param {!_module=} parent
 */
var _module = function(id, parent) {};
/** @type {!Array<string>} */
_module.builtinModules;
/**
 * Provides general utility methods when interacting with instances of Module — the module variable often seen in file modules. Accessed via require('module').
 * @type {typeof _module}
 */
_module.Module;

/**
 * @return {void}
 */
_module.runMain = function() {};

/**
 * @param {string} code
 * @return {string}
 */
_module.wrap = function(code) {};
