/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/_module.d.ts:
/**
 * @constructor
 * @struct
 * @param {string} id
 * @param {!_module=} parent
 */
var _module = function(id, parent) {};
/** @type {!Array<string>} */
_module.builtinModules;
/** @type {function(new: (!_module), string, !_module=): ?} */
_module.Module;
/** @type {?} */
_module.prototype.exports;
/** @type {!NodeRequireFunction} */
_module.prototype.require;
/** @type {string} */
_module.prototype.id;
/** @type {string} */
_module.prototype.filename;
/** @type {boolean} */
_module.prototype.loaded;
/** @type {!_module} */
_module.prototype.parent;
/** @type {!Array<!_module>} */
_module.prototype.children;
/** @type {!Array<string>} */
_module.prototype.paths;

/**
 * @return {void}
 */
_module.runMain = function() {};

/**
 * @param {string} code
 * @return {string}
 */
_module.wrap = function(code) {};
