/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/assert.d.ts:
// Derived from: declare module "assert"
/**
 * @param {?} value
 * @param {string=} message
 * @return {void}
 */
var assert = function(value, message) {};

/**
 * @extends {Error}
 * @constructor
 * @struct
 * @param {{message: string, actual: ?, expected: ?, operator: string, stackStartFn: !Function}=} options
 */
assert.AssertionError = function(options) {};
/** @type {string} */
assert.AssertionError.prototype.name;
/** @type {string} */
assert.AssertionError.prototype.message;
/** @type {?} */
assert.AssertionError.prototype.actual;
/** @type {?} */
assert.AssertionError.prototype.expected;
/** @type {string} */
assert.AssertionError.prototype.operator;
/** @type {boolean} */
assert.AssertionError.prototype.generatedMessage;
/** @type {string} */
assert.AssertionError.prototype.code;

/**
 * @param {string|?=} message_or_actual
 * @param {?=} expected
 * @param {string=} message
 * @param {string=} operator
 * @param {!Function=} stackStartFn
 * @return {?}
 */
assert.fail = function(message_or_actual, expected, message, operator, stackStartFn) {};

/**
 * @param {?} value
 * @param {string=} message
 * @return {void}
 */
assert.ok = function(value, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.equal = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.notEqual = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.deepEqual = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.notDeepEqual = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.strictEqual = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.notStrictEqual = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.deepStrictEqual = function(actual, expected, message) {};

/**
 * @param {?} actual
 * @param {?} expected
 * @param {string=} message
 * @return {void}
 */
assert.notDeepStrictEqual = function(actual, expected, message) {};

/**
 * @param {!Function} block
 * @param {string|(!Function|!RegExp)=} message_or_error
 * @param {string=} message
 * @return {void}
 */
assert.throws = function(block, message_or_error, message) {};

/**
 * @param {!Function} block
 * @param {string|(!Function|!RegExp)=} message_or_error
 * @param {string=} message
 * @return {void}
 */
assert.doesNotThrow = function(block, message_or_error, message) {};

/**
 * @param {?} value
 * @return {void}
 */
assert.ifError = function(value) {};
