/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/constants.d.ts:
// Derived from: declare module "constants"
/** @const */
var constants = {};
/** @type {number} */
constants.E2BIG;
/** @type {number} */
constants.EACCES;
/** @type {number} */
constants.EADDRINUSE;
/** @type {number} */
constants.EADDRNOTAVAIL;
/** @type {number} */
constants.EAFNOSUPPORT;
/** @type {number} */
constants.EAGAIN;
/** @type {number} */
constants.EALREADY;
/** @type {number} */
constants.EBADF;
/** @type {number} */
constants.EBADMSG;
/** @type {number} */
constants.EBUSY;
/** @type {number} */
constants.ECANCELED;
/** @type {number} */
constants.ECHILD;
/** @type {number} */
constants.ECONNABORTED;
/** @type {number} */
constants.ECONNREFUSED;
/** @type {number} */
constants.ECONNRESET;
/** @type {number} */
constants.EDEADLK;
/** @type {number} */
constants.EDESTADDRREQ;
/** @type {number} */
constants.EDOM;
/** @type {number} */
constants.EEXIST;
/** @type {number} */
constants.EFAULT;
/** @type {number} */
constants.EFBIG;
/** @type {number} */
constants.EHOSTUNREACH;
/** @type {number} */
constants.EIDRM;
/** @type {number} */
constants.EILSEQ;
/** @type {number} */
constants.EINPROGRESS;
/** @type {number} */
constants.EINTR;
/** @type {number} */
constants.EINVAL;
/** @type {number} */
constants.EIO;
/** @type {number} */
constants.EISCONN;
/** @type {number} */
constants.EISDIR;
/** @type {number} */
constants.ELOOP;
/** @type {number} */
constants.EMFILE;
/** @type {number} */
constants.EMLINK;
/** @type {number} */
constants.EMSGSIZE;
/** @type {number} */
constants.ENAMETOOLONG;
/** @type {number} */
constants.ENETDOWN;
/** @type {number} */
constants.ENETRESET;
/** @type {number} */
constants.ENETUNREACH;
/** @type {number} */
constants.ENFILE;
/** @type {number} */
constants.ENOBUFS;
/** @type {number} */
constants.ENODATA;
/** @type {number} */
constants.ENODEV;
/** @type {number} */
constants.ENOENT;
/** @type {number} */
constants.ENOEXEC;
/** @type {number} */
constants.ENOLCK;
/** @type {number} */
constants.ENOLINK;
/** @type {number} */
constants.ENOMEM;
/** @type {number} */
constants.ENOMSG;
/** @type {number} */
constants.ENOPROTOOPT;
/** @type {number} */
constants.ENOSPC;
/** @type {number} */
constants.ENOSR;
/** @type {number} */
constants.ENOSTR;
/** @type {number} */
constants.ENOSYS;
/** @type {number} */
constants.ENOTCONN;
/** @type {number} */
constants.ENOTDIR;
/** @type {number} */
constants.ENOTEMPTY;
/** @type {number} */
constants.ENOTSOCK;
/** @type {number} */
constants.ENOTSUP;
/** @type {number} */
constants.ENOTTY;
/** @type {number} */
constants.ENXIO;
/** @type {number} */
constants.EOPNOTSUPP;
/** @type {number} */
constants.EOVERFLOW;
/** @type {number} */
constants.EPERM;
/** @type {number} */
constants.EPIPE;
/** @type {number} */
constants.EPROTO;
/** @type {number} */
constants.EPROTONOSUPPORT;
/** @type {number} */
constants.EPROTOTYPE;
/** @type {number} */
constants.ERANGE;
/** @type {number} */
constants.EROFS;
/** @type {number} */
constants.ESPIPE;
/** @type {number} */
constants.ESRCH;
/** @type {number} */
constants.ETIME;
/** @type {number} */
constants.ETIMEDOUT;
/** @type {number} */
constants.ETXTBSY;
/** @type {number} */
constants.EWOULDBLOCK;
/** @type {number} */
constants.EXDEV;
/** @type {number} */
constants.WSAEINTR;
/** @type {number} */
constants.WSAEBADF;
/** @type {number} */
constants.WSAEACCES;
/** @type {number} */
constants.WSAEFAULT;
/** @type {number} */
constants.WSAEINVAL;
/** @type {number} */
constants.WSAEMFILE;
/** @type {number} */
constants.WSAEWOULDBLOCK;
/** @type {number} */
constants.WSAEINPROGRESS;
/** @type {number} */
constants.WSAEALREADY;
/** @type {number} */
constants.WSAENOTSOCK;
/** @type {number} */
constants.WSAEDESTADDRREQ;
/** @type {number} */
constants.WSAEMSGSIZE;
/** @type {number} */
constants.WSAEPROTOTYPE;
/** @type {number} */
constants.WSAENOPROTOOPT;
/** @type {number} */
constants.WSAEPROTONOSUPPORT;
/** @type {number} */
constants.WSAESOCKTNOSUPPORT;
/** @type {number} */
constants.WSAEOPNOTSUPP;
/** @type {number} */
constants.WSAEPFNOSUPPORT;
/** @type {number} */
constants.WSAEAFNOSUPPORT;
/** @type {number} */
constants.WSAEADDRINUSE;
/** @type {number} */
constants.WSAEADDRNOTAVAIL;
/** @type {number} */
constants.WSAENETDOWN;
/** @type {number} */
constants.WSAENETUNREACH;
/** @type {number} */
constants.WSAENETRESET;
/** @type {number} */
constants.WSAECONNABORTED;
/** @type {number} */
constants.WSAECONNRESET;
/** @type {number} */
constants.WSAENOBUFS;
/** @type {number} */
constants.WSAEISCONN;
/** @type {number} */
constants.WSAENOTCONN;
/** @type {number} */
constants.WSAESHUTDOWN;
/** @type {number} */
constants.WSAETOOMANYREFS;
/** @type {number} */
constants.WSAETIMEDOUT;
/** @type {number} */
constants.WSAECONNREFUSED;
/** @type {number} */
constants.WSAELOOP;
/** @type {number} */
constants.WSAENAMETOOLONG;
/** @type {number} */
constants.WSAEHOSTDOWN;
/** @type {number} */
constants.WSAEHOSTUNREACH;
/** @type {number} */
constants.WSAENOTEMPTY;
/** @type {number} */
constants.WSAEPROCLIM;
/** @type {number} */
constants.WSAEUSERS;
/** @type {number} */
constants.WSAEDQUOT;
/** @type {number} */
constants.WSAESTALE;
/** @type {number} */
constants.WSAEREMOTE;
/** @type {number} */
constants.WSASYSNOTREADY;
/** @type {number} */
constants.WSAVERNOTSUPPORTED;
/** @type {number} */
constants.WSANOTINITIALISED;
/** @type {number} */
constants.WSAEDISCON;
/** @type {number} */
constants.WSAENOMORE;
/** @type {number} */
constants.WSAECANCELLED;
/** @type {number} */
constants.WSAEINVALIDPROCTABLE;
/** @type {number} */
constants.WSAEINVALIDPROVIDER;
/** @type {number} */
constants.WSAEPROVIDERFAILEDINIT;
/** @type {number} */
constants.WSASYSCALLFAILURE;
/** @type {number} */
constants.WSASERVICE_NOT_FOUND;
/** @type {number} */
constants.WSATYPE_NOT_FOUND;
/** @type {number} */
constants.WSA_E_NO_MORE;
/** @type {number} */
constants.WSA_E_CANCELLED;
/** @type {number} */
constants.WSAEREFUSED;
/** @type {number} */
constants.SIGHUP;
/** @type {number} */
constants.SIGINT;
/** @type {number} */
constants.SIGILL;
/** @type {number} */
constants.SIGABRT;
/** @type {number} */
constants.SIGFPE;
/** @type {number} */
constants.SIGKILL;
/** @type {number} */
constants.SIGSEGV;
/** @type {number} */
constants.SIGTERM;
/** @type {number} */
constants.SIGBREAK;
/** @type {number} */
constants.SIGWINCH;
/** @type {number} */
constants.SSL_OP_ALL;
/** @type {number} */
constants.SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION;
/** @type {number} */
constants.SSL_OP_CIPHER_SERVER_PREFERENCE;
/** @type {number} */
constants.SSL_OP_CISCO_ANYCONNECT;
/** @type {number} */
constants.SSL_OP_COOKIE_EXCHANGE;
/** @type {number} */
constants.SSL_OP_CRYPTOPRO_TLSEXT_BUG;
/** @type {number} */
constants.SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS;
/** @type {number} */
constants.SSL_OP_EPHEMERAL_RSA;
/** @type {number} */
constants.SSL_OP_LEGACY_SERVER_CONNECT;
/** @type {number} */
constants.SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER;
/** @type {number} */
constants.SSL_OP_MICROSOFT_SESS_ID_BUG;
/** @type {number} */
constants.SSL_OP_MSIE_SSLV2_RSA_PADDING;
/** @type {number} */
constants.SSL_OP_NETSCAPE_CA_DN_BUG;
/** @type {number} */
constants.SSL_OP_NETSCAPE_CHALLENGE_BUG;
/** @type {number} */
constants.SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG;
/** @type {number} */
constants.SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG;
/** @type {number} */
constants.SSL_OP_NO_COMPRESSION;
/** @type {number} */
constants.SSL_OP_NO_QUERY_MTU;
/** @type {number} */
constants.SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION;
/** @type {number} */
constants.SSL_OP_NO_SSLv2;
/** @type {number} */
constants.SSL_OP_NO_SSLv3;
/** @type {number} */
constants.SSL_OP_NO_TICKET;
/** @type {number} */
constants.SSL_OP_NO_TLSv1;
/** @type {number} */
constants.SSL_OP_NO_TLSv1_1;
/** @type {number} */
constants.SSL_OP_NO_TLSv1_2;
/** @type {number} */
constants.SSL_OP_PKCS1_CHECK_1;
/** @type {number} */
constants.SSL_OP_PKCS1_CHECK_2;
/** @type {number} */
constants.SSL_OP_SINGLE_DH_USE;
/** @type {number} */
constants.SSL_OP_SINGLE_ECDH_USE;
/** @type {number} */
constants.SSL_OP_SSLEAY_080_CLIENT_DH_BUG;
/** @type {number} */
constants.SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG;
/** @type {number} */
constants.SSL_OP_TLS_BLOCK_PADDING_BUG;
/** @type {number} */
constants.SSL_OP_TLS_D5_BUG;
/** @type {number} */
constants.SSL_OP_TLS_ROLLBACK_BUG;
/** @type {number} */
constants.ENGINE_METHOD_DSA;
/** @type {number} */
constants.ENGINE_METHOD_DH;
/** @type {number} */
constants.ENGINE_METHOD_RAND;
/** @type {number} */
constants.ENGINE_METHOD_ECDH;
/** @type {number} */
constants.ENGINE_METHOD_ECDSA;
/** @type {number} */
constants.ENGINE_METHOD_CIPHERS;
/** @type {number} */
constants.ENGINE_METHOD_DIGESTS;
/** @type {number} */
constants.ENGINE_METHOD_STORE;
/** @type {number} */
constants.ENGINE_METHOD_PKEY_METHS;
/** @type {number} */
constants.ENGINE_METHOD_PKEY_ASN1_METHS;
/** @type {number} */
constants.ENGINE_METHOD_ALL;
/** @type {number} */
constants.ENGINE_METHOD_NONE;
/** @type {number} */
constants.DH_CHECK_P_NOT_SAFE_PRIME;
/** @type {number} */
constants.DH_CHECK_P_NOT_PRIME;
/** @type {number} */
constants.DH_UNABLE_TO_CHECK_GENERATOR;
/** @type {number} */
constants.DH_NOT_SUITABLE_GENERATOR;
/** @type {number} */
constants.NPN_ENABLED;
/** @type {number} */
constants.RSA_PKCS1_PADDING;
/** @type {number} */
constants.RSA_SSLV23_PADDING;
/** @type {number} */
constants.RSA_NO_PADDING;
/** @type {number} */
constants.RSA_PKCS1_OAEP_PADDING;
/** @type {number} */
constants.RSA_X931_PADDING;
/** @type {number} */
constants.RSA_PKCS1_PSS_PADDING;
/** @type {number} */
constants.POINT_CONVERSION_COMPRESSED;
/** @type {number} */
constants.POINT_CONVERSION_UNCOMPRESSED;
/** @type {number} */
constants.POINT_CONVERSION_HYBRID;
/** @type {number} */
constants.O_RDONLY;
/** @type {number} */
constants.O_WRONLY;
/** @type {number} */
constants.O_RDWR;
/** @type {number} */
constants.S_IFMT;
/** @type {number} */
constants.S_IFREG;
/** @type {number} */
constants.S_IFDIR;
/** @type {number} */
constants.S_IFCHR;
/** @type {number} */
constants.S_IFBLK;
/** @type {number} */
constants.S_IFIFO;
/** @type {number} */
constants.S_IFSOCK;
/** @type {number} */
constants.S_IRWXU;
/** @type {number} */
constants.S_IRUSR;
/** @type {number} */
constants.S_IWUSR;
/** @type {number} */
constants.S_IXUSR;
/** @type {number} */
constants.S_IRWXG;
/** @type {number} */
constants.S_IRGRP;
/** @type {number} */
constants.S_IWGRP;
/** @type {number} */
constants.S_IXGRP;
/** @type {number} */
constants.S_IRWXO;
/** @type {number} */
constants.S_IROTH;
/** @type {number} */
constants.S_IWOTH;
/** @type {number} */
constants.S_IXOTH;
/** @type {number} */
constants.S_IFLNK;
/** @type {number} */
constants.O_CREAT;
/** @type {number} */
constants.O_EXCL;
/** @type {number} */
constants.O_NOCTTY;
/** @type {number} */
constants.O_DIRECTORY;
/** @type {number} */
constants.O_NOATIME;
/** @type {number} */
constants.O_NOFOLLOW;
/** @type {number} */
constants.O_SYNC;
/** @type {number} */
constants.O_DSYNC;
/** @type {number} */
constants.O_SYMLINK;
/** @type {number} */
constants.O_DIRECT;
/** @type {number} */
constants.O_NONBLOCK;
/** @type {number} */
constants.O_TRUNC;
/** @type {number} */
constants.O_APPEND;
/** @type {number} */
constants.F_OK;
/** @type {number} */
constants.R_OK;
/** @type {number} */
constants.W_OK;
/** @type {number} */
constants.X_OK;
/** @type {number} */
constants.UV_UDP_REUSEADDR;
/** @type {number} */
constants.SIGQUIT;
/** @type {number} */
constants.SIGTRAP;
/** @type {number} */
constants.SIGIOT;
/** @type {number} */
constants.SIGBUS;
/** @type {number} */
constants.SIGUSR1;
/** @type {number} */
constants.SIGUSR2;
/** @type {number} */
constants.SIGPIPE;
/** @type {number} */
constants.SIGALRM;
/** @type {number} */
constants.SIGCHLD;
/** @type {number} */
constants.SIGSTKFLT;
/** @type {number} */
constants.SIGCONT;
/** @type {number} */
constants.SIGSTOP;
/** @type {number} */
constants.SIGTSTP;
/** @type {number} */
constants.SIGTTIN;
/** @type {number} */
constants.SIGTTOU;
/** @type {number} */
constants.SIGURG;
/** @type {number} */
constants.SIGXCPU;
/** @type {number} */
constants.SIGXFSZ;
/** @type {number} */
constants.SIGVTALRM;
/** @type {number} */
constants.SIGPROF;
/** @type {number} */
constants.SIGIO;
/** @type {number} */
constants.SIGPOLL;
/** @type {number} */
constants.SIGPWR;
/** @type {number} */
constants.SIGSYS;
/** @type {number} */
constants.SIGUNUSED;
/** @type {string} */
constants.defaultCoreCipherList;
/** @type {string} */
constants.defaultCipherList;
/** @type {number} */
constants.ENGINE_METHOD_RSA;
/** @type {number} */
constants.ALPN_ENABLED;
