/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/domain.d.ts:
// Derived from: declare module "domain"
/** @const */
var domain = {};
/**
 * @extends {events.EventEmitter}
 * @implements {NodeJS.Domain}
 * @constructor
 * @struct
 */
domain.Domain = function() {};
/** @type {!Array<?>} */
domain.Domain.prototype.members;

/**
 * @param {!Function} fn
 * @return {void}
 */
domain.Domain.prototype.run = function(fn) {};

/**
 * @param {!events.EventEmitter} emitter
 * @return {void}
 */
domain.Domain.prototype.add = function(emitter) {};

/**
 * @param {!events.EventEmitter} emitter
 * @return {void}
 */
domain.Domain.prototype.remove = function(emitter) {};

/**
 * @param {function(!Error, ?): ?} cb
 * @return {?}
 */
domain.Domain.prototype.bind = function(cb) {};

/**
 * @param {function(?): ?} cb
 * @return {?}
 */
domain.Domain.prototype.intercept = function(cb) {};

/**
 * @return {void}
 */
domain.Domain.prototype.dispose = function() {};

/**
 * @return {void}
 */
domain.Domain.prototype.enter = function() {};

/**
 * @return {void}
 */
domain.Domain.prototype.exit = function() {};

/**
 * @return {!domain.Domain}
 */
domain.create = function() {};
