/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/global.d.ts:
/** @type {!NodeJS.ConsoleConstructor} */
Console.prototype.Console;

/**
 * @param {?} value
 * @param {string=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.assert = function(value, message, optionalParams) {};

/**
 * @return {void}
 */
Console.prototype.clear = function() {};

/**
 * @param {string=} label
 * @return {void}
 */
Console.prototype.count = function(label) {};

/**
 * @param {string=} label
 * @return {void}
 */
Console.prototype.countReset = function(label) {};

/**
 * @param {?=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.debug = function(message, optionalParams) {};

/**
 * @param {?} obj
 * @param {!NodeJS.InspectOptions=} options
 * @return {void}
 */
Console.prototype.dir = function(obj, options) {};

/**
 * @param {?=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.error = function(message, optionalParams) {};

/**
 * @param {...?} label
 * @return {void}
 */
Console.prototype.group = function(label) {};

/**
 * @return {void}
 */
Console.prototype.groupCollapsed = function() {};

/**
 * @return {void}
 */
Console.prototype.groupEnd = function() {};

/**
 * @param {?=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.info = function(message, optionalParams) {};

/**
 * @param {?=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.log = function(message, optionalParams) {};

/**
 * @param {string} label
 * @return {void}
 */
Console.prototype.time = function(label) {};

/**
 * @param {string} label
 * @return {void}
 */
Console.prototype.timeEnd = function(label) {};

/**
 * @param {?=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.trace = function(message, optionalParams) {};

/**
 * @param {?=} message
 * @param {...?} optionalParams
 * @return {void}
 */
Console.prototype.warn = function(message, optionalParams) {};

/**
 * @deprecated Use console.timeStamp() instead.
 * @param {string=} label
 * @return {void}
 */
Console.prototype.markTimeline = function(label) {};

/**
 * @param {string=} label
 * @return {void}
 */
Console.prototype.profile = function(label) {};

/**
 * @param {string=} label
 * @return {void}
 */
Console.prototype.profileEnd = function(label) {};

/**
 * @param {string=} label
 * @return {void}
 */
Console.prototype.timeStamp = function(label) {};

/**
 * @deprecated Use console.time() instead.
 * @param {string=} label
 * @return {void}
 */
Console.prototype.timeline = function(label) {};

/**
 * @deprecated Use console.timeEnd() instead.
 * @param {string=} label
 * @return {void}
 */
Console.prototype.timelineEnd = function(label) {};
/** @type {string} */
Error.prototype.stack;

/**
 * Removes whitespace from the left end of a string.
 * @return {string}
 */
String.prototype.trimLeft = function() {};

/**
 * Removes whitespace from the right end of a string.
 * @return {string}
 */
String.prototype.trimRight = function() {};
/** @type {!NodeJS.Process} */
var process;
/** @type {!Console} */
var console;
/** @type {string} */
var __filename;
/** @type {string} */
var __dirname;

/**
 * @template T
 * @param {number} ms
 * @param {T=} value
 * @return {!Promise<void>|!Promise<T>}
 */
setTimeout.__promisify__ = function(ms, value) {};

/**
 * @param {function(...?): void} callback
 * @param {...?} args
 * @return {?}
 */
function setImmediate(callback, args) {}

/**
 * @template T
 * @param {T=} value
 * @return {!Promise<void>|!Promise<T>}
 */
setImmediate.__promisify__ = function(value) {};

/**
 * @param {?} immediateId
 * @return {void}
 */
function clearImmediate(immediateId) {}
/** @type {function(new: (!Buffer), string, string=): ?} */
var SlowBuffer;
/**
 * @record
 * @struct
 */
function MapConstructor() {}
/**
 * @record
 * @struct
 */
function WeakMapConstructor() {}
/**
 * @record
 * @struct
 */
function SetConstructor() {}
/**
 * @record
 * @struct
 */
function WeakSetConstructor() {}
/**
 * @template T
 * @record
 * @struct
 */
function Iterable() {}
/**
 * @template T
 * @record
 * @struct
 */
function Iterator() {}

/**
 * @param {?=} value
 * @return {!IteratorResult<T>}
 */
Iterator.prototype.next = function(value) {};
/**
 * @template T
 * @record
 * @struct
 */
function IteratorResult() {}
/**
 * @record
 * @struct
 */
function SymbolConstructor() {}
/** @type {symbol} */
SymbolConstructor.prototype.iterator;
/**
 * @template T
 * @record
 * @struct
 */
function IterableIterator() {}
/**
 * @record
 * @struct
 */
function NodeRequireFunction() {}

/* TODO: CallSignature:  */
/**
 * @extends {NodeRequireFunction}
 * @record
 * @struct
 */
function NodeRequire() {}
/** @type {!RequireResolve} */
NodeRequire.prototype.resolve;
/** @type {?} */
NodeRequire.prototype.cache;
/** @type {!NodeExtensions} */
NodeRequire.prototype.extensions;
/** @type {!NodeModule} */
NodeRequire.prototype.main;
/**
 * @record
 * @struct
 */
function RequireResolve() {}

/* TODO: CallSignature:  */

/**
 * @param {string} request
 * @return {!Array<string>}
 */
RequireResolve.prototype.paths = function(request) {};
/**
 * @record
 * @struct
 */
function NodeExtensions() {}

/* TODO: PropertySignature: '.js' */

/* TODO: PropertySignature: '.json' */

/* TODO: PropertySignature: '.node' */

/* TODO: IndexSignature:  */
/** @type {!NodeRequire} */
var require;
/**
 * @record
 * @struct
 */
function NodeModule() {}
/** @type {?} */
NodeModule.prototype.exports;
/** @type {!NodeRequireFunction} */
NodeModule.prototype.require;
/** @type {string} */
NodeModule.prototype.id;
/** @type {string} */
NodeModule.prototype.filename;
/** @type {boolean} */
NodeModule.prototype.loaded;
/** @type {!NodeModule} */
NodeModule.prototype.parent;
/** @type {!Array<!NodeModule>} */
NodeModule.prototype.children;
/** @type {!Array<string>} */
NodeModule.prototype.paths;
/** @type {!NodeRequire} */
var require;
/** @type {?} */
NodeModule.prototype.exports;
/** @type {!NodeRequireFunction} */
NodeModule.prototype.require;
/** @type {string} */
NodeModule.prototype.id;
/** @type {string} */
NodeModule.prototype.filename;
/** @type {boolean} */
NodeModule.prototype.loaded;
/** @type {!NodeModule} */
NodeModule.prototype.parent;
/** @type {!Array<!NodeModule>} */
NodeModule.prototype.children;
/** @type {!Array<string>} */
NodeModule.prototype.paths;

/** @typedef {string} */
var BufferEncoding;
/**
 * @extends {NodeBuffer}
 * @record
 * @struct
 */
function Buffer() {}
/**
 * @record
 * @struct
 */
function NodeBuffer() {}

/**
 * @param {string} string
 * @param {number=} offset
 * @param {number=} length
 * @param {string=} encoding
 * @return {number}
 */
NodeBuffer.prototype.write = function(string, offset, length, encoding) {};

/**
 * @param {string=} encoding
 * @param {number=} start
 * @param {number=} end
 * @return {string}
 */
NodeBuffer.prototype.toString = function(encoding, start, end) {};

/**
 * @return {{type: string, data: !Array<?>}}
 */
NodeBuffer.prototype.toJSON = function() {};

/**
 * @param {!Buffer} otherBuffer
 * @return {boolean}
 */
NodeBuffer.prototype.equals = function(otherBuffer) {};

/**
 * @param {!Buffer} otherBuffer
 * @param {number=} targetStart
 * @param {number=} targetEnd
 * @param {number=} sourceStart
 * @param {number=} sourceEnd
 * @return {number}
 */
NodeBuffer.prototype.compare = function(otherBuffer, targetStart, targetEnd, sourceStart, sourceEnd) {};

/**
 * @param {!Buffer} targetBuffer
 * @param {number=} targetStart
 * @param {number=} sourceStart
 * @param {number=} sourceEnd
 * @return {number}
 */
NodeBuffer.prototype.copy = function(targetBuffer, targetStart, sourceStart, sourceEnd) {};

/**
 * @param {number=} start
 * @param {number=} end
 * @return {!Buffer}
 */
NodeBuffer.prototype.slice = function(start, end) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUIntLE = function(value, offset, byteLength, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUIntBE = function(value, offset, byteLength, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeIntLE = function(value, offset, byteLength, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeIntBE = function(value, offset, byteLength, noAssert) {};

/**
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUIntLE = function(offset, byteLength, noAssert) {};

/**
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUIntBE = function(offset, byteLength, noAssert) {};

/**
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readIntLE = function(offset, byteLength, noAssert) {};

/**
 * @param {number} offset
 * @param {number} byteLength
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readIntBE = function(offset, byteLength, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUInt8 = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUInt16LE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUInt16BE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUInt32LE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readUInt32BE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readInt8 = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readInt16LE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readInt16BE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readInt32LE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readInt32BE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readFloatLE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readFloatBE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readDoubleLE = function(offset, noAssert) {};

/**
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.readDoubleBE = function(offset, noAssert) {};

/**
 * @return {!Buffer}
 */
NodeBuffer.prototype.swap16 = function() {};

/**
 * @return {!Buffer}
 */
NodeBuffer.prototype.swap32 = function() {};

/**
 * @return {!Buffer}
 */
NodeBuffer.prototype.swap64 = function() {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUInt8 = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUInt16LE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUInt16BE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUInt32LE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeUInt32BE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeInt8 = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeInt16LE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeInt16BE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeInt32LE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeInt32BE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeFloatLE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeFloatBE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeDoubleLE = function(value, offset, noAssert) {};

/**
 * @param {number} value
 * @param {number} offset
 * @param {boolean=} noAssert
 * @return {number}
 */
NodeBuffer.prototype.writeDoubleBE = function(value, offset, noAssert) {};

/**
 * @template THIS
 * @this {THIS}
 * @param {?} value
 * @param {number=} offset
 * @param {number=} end
 * @return {THIS}
 */
NodeBuffer.prototype.fill = function(value, offset, end) {};

/**
 * @param {(string|number|!Buffer)} value
 * @param {number=} byteOffset
 * @param {string=} encoding
 * @return {number}
 */
NodeBuffer.prototype.indexOf = function(value, byteOffset, encoding) {};

/**
 * @param {(string|number|!Buffer)} value
 * @param {number=} byteOffset
 * @param {string=} encoding
 * @return {number}
 */
NodeBuffer.prototype.lastIndexOf = function(value, byteOffset, encoding) {};

/**
 * @return {!IterableIterator<!Array<?>>}
 */
NodeBuffer.prototype.entries = function() {};

/**
 * @param {(string|number|!Buffer)} value
 * @param {number=} byteOffset
 * @param {string=} encoding
 * @return {boolean}
 */
NodeBuffer.prototype.includes = function(value, byteOffset, encoding) {};

/**
 * @return {!IterableIterator<number>}
 */
NodeBuffer.prototype.keys = function() {};

/**
 * @return {!IterableIterator<number>}
 */
NodeBuffer.prototype.values = function() {};
