/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/path.d.ts:
// Derived from: declare module "path"
/** @const */
var path = {};
/**
 * @record
 * @struct
 */
path.ParsedPath = function() {};
/** @type {string} */
path.ParsedPath.prototype.root;
/** @type {string} */
path.ParsedPath.prototype.dir;
/** @type {string} */
path.ParsedPath.prototype.base;
/** @type {string} */
path.ParsedPath.prototype.ext;
/** @type {string} */
path.ParsedPath.prototype.name;
/**
 * @record
 * @struct
 */
path.FormatInputPathObject = function() {};
/** @type {string} */
path.FormatInputPathObject.prototype.root;
/** @type {string} */
path.FormatInputPathObject.prototype.dir;
/** @type {string} */
path.FormatInputPathObject.prototype.base;
/** @type {string} */
path.FormatInputPathObject.prototype.ext;
/** @type {string} */
path.FormatInputPathObject.prototype.name;

/**
 * Normalize a string path, reducing '..' and '.' parts.
 * When multiple slashes are found, they're replaced by a single one; when the path contains a trailing slash, it is preserved. On Windows backslashes are used.
 * 
 * @param {string} p string path to normalize.
 * @return {string}
 */
path.normalize = function(p) {};

/**
 * Join all arguments together and normalize the resulting path.
 * Arguments must be strings. In v0.8, non-string arguments were silently ignored. In v0.10 and up, an exception is thrown.
 * 
 * @param {...string} paths paths to join.
 * @return {string}
 */
path.join = function(paths) {};

/**
 * The right-most parameter is considered {to}.  Other parameters are considered an array of {from}.
 * 
 * Starting from leftmost {from} parameter, resolves {to} to an absolute path.
 * 
 * If {to} isn't already absolute, {from} arguments are prepended in right to left order, until an absolute path is found. If after using all {from} paths still no absolute path is found, the current working directory is used as well. The resulting path is normalized, and trailing slashes are removed unless the path gets resolved to the root directory.
 * 
 * @param {...string} pathSegments string paths to join.  Non-string arguments are ignored.
 * @return {string}
 */
path.resolve = function(pathSegments) {};

/**
 * Determines whether {path} is an absolute path. An absolute path will always resolve to the same location, regardless of the working directory.
 * 
 * @param {string} path path to test.
 * @return {boolean}
 */
path.isAbsolute = function(path) {};

/**
 * Solve the relative path from {from} to {to}.
 * At times we have two absolute paths, and we need to derive the relative path from one to the other. This is actually the reverse transform of path.resolve.
 * @param {string} from
 * @param {string} to
 * @return {string}
 */
path.relative = function(from, to) {};

/**
 * Return the directory name of a path. Similar to the Unix dirname command.
 * 
 * @param {string} p the path to evaluate.
 * @return {string}
 */
path.dirname = function(p) {};

/**
 * Return the last portion of a path. Similar to the Unix basename command.
 * Often used to extract the file name from a fully qualified path.
 * 
 * @param {string} p the path to evaluate.
 * @param {string=} ext optionally, an extension to remove from the result.
 * @return {string}
 */
path.basename = function(p, ext) {};

/**
 * Return the extension of the path, from the last '.' to end of string in the last portion of the path.
 * If there is no '.' in the last portion of the path or the first character of it is '.', then it returns an empty string
 * 
 * @param {string} p the path to evaluate.
 * @return {string}
 */
path.extname = function(p) {};
/** @type {string} */
path.sep;
/** @type {string} */
path.delimiter;

/**
 * Returns an object from a path string - the opposite of format().
 * 
 * @param {string} pathString path to evaluate.
 * @return {!path.ParsedPath}
 */
path.parse = function(pathString) {};

/**
 * Returns a path string from an object - the opposite of parse().
 * 
 * @param {!path.FormatInputPathObject} pathObject
 * @return {string}
 */
path.format = function(pathObject) {};
/** @const */
path.posix = {};

/**
 * @param {string} p
 * @return {string}
 */
path.posix.normalize = function(p) {};

/**
 * @param {...?} paths
 * @return {string}
 */
path.posix.join = function(paths) {};

/**
 * @param {...?} pathSegments
 * @return {string}
 */
path.posix.resolve = function(pathSegments) {};

/**
 * @param {string} p
 * @return {boolean}
 */
path.posix.isAbsolute = function(p) {};

/**
 * @param {string} from
 * @param {string} to
 * @return {string}
 */
path.posix.relative = function(from, to) {};

/**
 * @param {string} p
 * @return {string}
 */
path.posix.dirname = function(p) {};

/**
 * @param {string} p
 * @param {string=} ext
 * @return {string}
 */
path.posix.basename = function(p, ext) {};

/**
 * @param {string} p
 * @return {string}
 */
path.posix.extname = function(p) {};
/** @type {string} */
path.posix.sep;
/** @type {string} */
path.posix.delimiter;

/**
 * @param {string} p
 * @return {!path.ParsedPath}
 */
path.posix.parse = function(p) {};

/**
 * @param {!path.FormatInputPathObject} pP
 * @return {string}
 */
path.posix.format = function(pP) {};
/** @const */
path.win32 = {};

/**
 * @param {string} p
 * @return {string}
 */
path.win32.normalize = function(p) {};

/**
 * @param {...?} paths
 * @return {string}
 */
path.win32.join = function(paths) {};

/**
 * @param {...?} pathSegments
 * @return {string}
 */
path.win32.resolve = function(pathSegments) {};

/**
 * @param {string} p
 * @return {boolean}
 */
path.win32.isAbsolute = function(p) {};

/**
 * @param {string} from
 * @param {string} to
 * @return {string}
 */
path.win32.relative = function(from, to) {};

/**
 * @param {string} p
 * @return {string}
 */
path.win32.dirname = function(p) {};

/**
 * @param {string} p
 * @param {string=} ext
 * @return {string}
 */
path.win32.basename = function(p, ext) {};

/**
 * @param {string} p
 * @return {string}
 */
path.win32.extname = function(p) {};
/** @type {string} */
path.win32.sep;
/** @type {string} */
path.win32.delimiter;

/**
 * @param {string} p
 * @return {!path.ParsedPath}
 */
path.win32.parse = function(p) {};

/**
 * @param {!path.FormatInputPathObject} pP
 * @return {string}
 */
path.win32.format = function(pP) {};
