/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/punycode.d.ts:
// Derived from: declare module "punycode"
/** @const */
var punycode = {};

/**
 * @param {string} string
 * @return {string}
 */
punycode.decode = function(string) {};

/**
 * @param {string} string
 * @return {string}
 */
punycode.encode = function(string) {};

/**
 * @param {string} domain
 * @return {string}
 */
punycode.toUnicode = function(domain) {};

/**
 * @param {string} domain
 * @return {string}
 */
punycode.toASCII = function(domain) {};
/** @type {?} */
punycode.ucs2;
/**
 * @record
 * @struct
 */
punycode.ucs2 = function() {};

/**
 * @param {string} string
 * @return {!Array<number>}
 */
punycode.ucs2.prototype.decode = function(string) {};

/**
 * @param {!Array<number>} codePoints
 * @return {string}
 */
punycode.ucs2.prototype.encode = function(codePoints) {};
/** @type {?} */
punycode.version;
