/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/tty.d.ts:
// Derived from: declare module "tty"
/** @const */
var tty = {};

/**
 * @param {number} fd
 * @return {boolean}
 */
tty.isatty = function(fd) {};
/**
 * @extends {net.Socket}
 * @constructor
 * @struct
 */
tty.ReadStream = function() {};
/** @type {boolean} */
tty.ReadStream.prototype.isRaw;
/** @type {boolean} */
tty.ReadStream.prototype.isTTY;

/**
 * @param {boolean} mode
 * @return {void}
 */
tty.ReadStream.prototype.setRawMode = function(mode) {};
/**
 * @extends {net.Socket}
 * @constructor
 * @struct
 */
tty.WriteStream = function() {};
/** @type {number} */
tty.WriteStream.prototype.columns;
/** @type {number} */
tty.WriteStream.prototype.rows;
/** @type {boolean} */
tty.WriteStream.prototype.isTTY;
