/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types-v8/v8.d.ts:
// Derived from: declare module "v8"
/** @const */
var v8 = {};
/**
 * @record
 * @struct
 */
v8.HeapSpaceInfo = function() {};
/** @type {string} */
v8.HeapSpaceInfo.prototype.space_name;
/** @type {number} */
v8.HeapSpaceInfo.prototype.space_size;
/** @type {number} */
v8.HeapSpaceInfo.prototype.space_used_size;
/** @type {number} */
v8.HeapSpaceInfo.prototype.space_available_size;
/** @type {number} */
v8.HeapSpaceInfo.prototype.physical_space_size;

/** @typedef {number} */
v8.DoesZapCodeSpaceFlag;
/**
 * @record
 * @struct
 */
v8.HeapInfo = function() {};
/** @type {number} */
v8.HeapInfo.prototype.total_heap_size;
/** @type {number} */
v8.HeapInfo.prototype.total_heap_size_executable;
/** @type {number} */
v8.HeapInfo.prototype.total_physical_size;
/** @type {number} */
v8.HeapInfo.prototype.total_available_size;
/** @type {number} */
v8.HeapInfo.prototype.used_heap_size;
/** @type {number} */
v8.HeapInfo.prototype.heap_size_limit;
/** @type {number} */
v8.HeapInfo.prototype.malloced_memory;
/** @type {number} */
v8.HeapInfo.prototype.peak_malloced_memory;
/** @type {number} */
v8.HeapInfo.prototype.does_zap_garbage;

/**
 * @return {!v8.HeapInfo}
 */
v8.getHeapStatistics = function() {};

/**
 * @return {!Array<!v8.HeapSpaceInfo>}
 */
v8.getHeapSpaceStatistics = function() {};

/**
 * @param {string} flags
 * @return {void}
 */
v8.setFlagsFromString = function(flags) {};
